name: "Moropo Test Run"
description: "Run tests on Moropo platform"
inputs:
  build_id:
    description: "Build ID"
    required: false
  expo_release_channel:
    description: "Expo Release Channel"
    required: false
  devices:
    description: "Array of device IDs"
    required: false
  test_ids:
    description: "Array of test IDs"
    required: false
  scheduled_test_id:
    description: "Test Run ID"
    required: true
  moropo_api_key:
    description: "Moropo API Key"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
